package ProyectoFileManager;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author diego
 */
public class Cruzar_panel extends javax.swing.JPanel {

    /**
     * Creates new form Cruzar_panel
     */
    public Cruzar_panel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        campos_list = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        archivos_list = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        directorio_seleccionado = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jScrollPane1.setViewportView(campos_list);

        add(jScrollPane1);
        jScrollPane1.setBounds(270, 30, 120, 150);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        archivos_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                archivos_listMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(archivos_list);

        add(jScrollPane2);
        jScrollPane2.setBounds(40, 120, 210, 60);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 150, 150));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Directorio Seleccionado:");
        add(jLabel1);
        jLabel1.setBounds(60, 20, 150, 15);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(150, 150, 150));
        jLabel2.setText("Campos Comunes:");
        add(jLabel2);
        jLabel2.setBounds(270, 10, 120, 16);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(150, 150, 150));
        jLabel3.setText("Archivos a Cruzar:");
        add(jLabel3);
        jLabel3.setBounds(40, 100, 120, 16);

        directorio_seleccionado.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        directorio_seleccionado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        directorio_seleccionado.setText("'Sin Seleccion'");
        add(directorio_seleccionado);
        directorio_seleccionado.setBounds(10, 40, 250, 15);

        jButton1.setText("Abrir Directorio");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(60, 60, 150, 23);

        jToggleButton1.setText("Guardar Como...");
        jToggleButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton1MouseClicked(evt);
            }
        });
        add(jToggleButton1);
        jToggleButton1.setBounds(120, 240, 113, 23);

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(80, 190, 73, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void archivos_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_archivos_listMouseClicked

    }//GEN-LAST:event_archivos_listMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        JFileChooser fc = new JFileChooser();
        if(!"\'Sin Seleccion\'".equals(directorio_seleccionado.getText()))
            fc.setCurrentDirectory(new java.io.File(directorio_seleccionado.getText()).getParentFile());
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        archivos_list.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        int return_val = fc.showDialog(this, "Choose");
        if(return_val == JFileChooser.APPROVE_OPTION){
            directorio_seleccionado.setText(fc.getSelectedFile().getPath());
            ArrayList<String> list = new ArrayList();
            for(String file : fc.getSelectedFile().list()){
                if(file.contains(".txt"))
                list.add(file);
            }
            archivos_list.setListData(new Vector(list));
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jToggleButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton1MouseClicked
         if("\'Sin Seleccion\'" == (directorio_seleccionado.getText())){
            return;
        }
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int return_val = fc.showSaveDialog(this);
        if(return_val == JFileChooser.APPROVE_OPTION){
            try{
                Cruce_archivos.cruzar(new ArrayList(campos_list.getSelectedValuesList()), fc.getSelectedFile().getPath());
            }catch(IOException e){}

        }
    }//GEN-LAST:event_jToggleButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        try{
            Cruce_archivos.leerArchivos(new ArrayList(archivos_list.getSelectedValuesList()));
            campos_list.setListData(new Vector(Cruce_archivos.getCamposComunes()));
        }catch(IOException e){}
    }//GEN-LAST:event_jButton2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> archivos_list;
    private javax.swing.JList<String> campos_list;
    private javax.swing.JLabel directorio_seleccionado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
