/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoFileManager;

import java.awt.BorderLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;

/**
 *
 * @author andre
 */
public class MenuCampos extends javax.swing.JPanel {

    /**
     * Creates new form MenuCampos
     */
    public MenuCampos() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel3.setVisible(false);
        botonCrear.setVisible(false);
        regresarCampos.setVisible(false);
        checkBoxSi.setVisible(false);
        checkBoxNo.setVisible(false);
        jSpinner1.setVisible(false);
        comboBoxTipo.setVisible(false);
        TextFieldNombre.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jListarCampos = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        borrarCamButton = new javax.swing.JButton();
        crearCamposButton = new javax.swing.JButton();
        modCamposButton = new javax.swing.JButton();
        listarCamposButton = new javax.swing.JButton();
        salirButton = new javax.swing.JButton();
        TextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        checkBoxSi = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        checkBoxNo = new javax.swing.JCheckBox();
        regresarCampos = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFileManager/document.png"))); // NOI18N
        jLabel1.setText("CAMPOS");
        add(jLabel1);
        jLabel1.setBounds(120, 20, 180, 40);

        borrarCamButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        borrarCamButton.setText("Borrar Campos");
        borrarCamButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarCamButtonMouseClicked(evt);
            }
        });
        borrarCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarCamButtonActionPerformed(evt);
            }
        });
        add(borrarCamButton);
        borrarCamButton.setBounds(120, 200, 180, 30);

        crearCamposButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        crearCamposButton.setText("Crear Campos");
        crearCamposButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                crearCamposButtonMouseClicked(evt);
            }
        });
        add(crearCamposButton);
        crearCamposButton.setBounds(120, 80, 180, 30);

        modCamposButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        modCamposButton.setText("Modificar Campos");
        modCamposButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modCamposButtonMouseClicked(evt);
            }
        });
        add(modCamposButton);
        modCamposButton.setBounds(120, 160, 180, 30);

        listarCamposButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        listarCamposButton.setText("Listar Campos");
        listarCamposButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listarCamposButtonMouseClicked(evt);
            }
        });
        add(listarCamposButton);
        listarCamposButton.setBounds(120, 120, 180, 30);

        salirButton.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        salirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFileManager/sign-out.png"))); // NOI18N
        salirButton.setText("Salir");
        salirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirButtonMouseClicked(evt);
            }
        });
        add(salirButton);
        salirButton.setBounds(290, 260, 110, 40);
        add(TextFieldNombre);
        TextFieldNombre.setBounds(140, 70, 160, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Llave Primaria:");
        add(jLabel3);
        jLabel3.setBounds(20, 160, 120, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Nombre del Campo:");
        add(jLabel4);
        jLabel4.setBounds(20, 70, 120, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tipo:");
        add(jLabel5);
        jLabel5.setBounds(20, 100, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Longitud:");
        add(jLabel6);
        jLabel6.setBounds(20, 130, 120, 20);

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Character", "Int" }));
        add(comboBoxTipo);
        comboBoxTipo.setBounds(140, 100, 100, 20);

        checkBoxSi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxSi.setText("Si");
        add(checkBoxSi);
        checkBoxSi.setBounds(140, 160, 40, 25);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel());
        add(jSpinner1);
        jSpinner1.setBounds(140, 130, 50, 20);

        checkBoxNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        checkBoxNo.setText("No");
        add(checkBoxNo);
        checkBoxNo.setBounds(190, 160, 43, 25);

        regresarCampos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        regresarCampos.setText("Regresar");
        regresarCampos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresarCamposMouseClicked(evt);
            }
        });
        add(regresarCampos);
        regresarCampos.setBounds(10, 270, 110, 30);

        botonCrear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCrear.setText("Crear Campo");
        botonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMouseClicked(evt);
            }
        });
        add(botonCrear);
        botonCrear.setBounds(140, 190, 120, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProyectoFileManager/Fondo.png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 410, 310);
    }// </editor-fold>//GEN-END:initComponents

    private void salirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirButtonMouseClicked
        MenuPrincipal mp = new MenuPrincipal();
        Main.frame.Panel(mp);
    }//GEN-LAST:event_salirButtonMouseClicked

    private void crearCamposButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearCamposButtonMouseClicked

        if (Main.open) {

            if (Main.cantRegis == 0) {
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                botonCrear.setVisible(true);
                regresarCampos.setVisible(true);
                jSpinner1.setVisible(true);
                comboBoxTipo.setVisible(true);
                TextFieldNombre.setVisible(true);
                jLabel1.setVisible(false);
                crearCamposButton.setVisible(false);
                listarCamposButton.setVisible(false);
                modCamposButton.setVisible(false);
                borrarCamButton.setVisible(false);
                salirButton.setVisible(false);
                if (Main.key.equals("")) {
                    jLabel3.setVisible(true);
                    checkBoxSi.setVisible(true);
                    checkBoxNo.setVisible(true);
                }
            } else {
                JOptionPane.showMessageDialog(null, "¡Archivo ya contiene registros!", "Archivos", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡No hay archivo abierto!", "Archivos", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_crearCamposButtonMouseClicked

    private void listarCamposButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listarCamposButtonMouseClicked
        if (Main.open) {
            Main.tipoCam = 1;
            TablaCampos tc = new TablaCampos();
            Main.frame.Panel(tc);

        } else {
            JOptionPane.showMessageDialog(null, "¡No hay archivo abierto!", "Archivos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_listarCamposButtonMouseClicked

    private void modCamposButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modCamposButtonMouseClicked
        if (Main.open) {
            if (Main.cantRegis == 0) {
                Main.tipoCam = 2;
                TablaCampos tc = new TablaCampos();
                Main.frame.Panel(tc);
            } else {
                JOptionPane.showMessageDialog(null, "¡Archivo ya contiene registros!", "Archivos", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡No hay archivo abierto!", "Archivos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modCamposButtonMouseClicked

    private void borrarCamButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarCamButtonMouseClicked
        if (Main.open) {
            if (Main.cantRegis == 0) {
                Main.tipoCam = 3;
                TablaCampos tc = new TablaCampos();
                Main.frame.Panel(tc);
            } else {
                JOptionPane.showMessageDialog(null, "¡Archivo ya contiene registros!", "Archivos", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "¡No hay archivo abierto!", "Archivos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_borrarCamButtonMouseClicked

    private void botonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseClicked

        int size = (int) jSpinner1.getValue();
        String name = TextFieldNombre.getText();
        String tipo = "";
        if (comboBoxTipo.getSelectedItem().equals("Character")) {
            tipo = "char";
        } else if (comboBoxTipo.getSelectedItem().equals("Int")) {
            tipo = "int";
        }
        if (!Main.key.equals("")) {
            jLabel3.setVisible(false);
            checkBoxSi.setVisible(false);
            checkBoxNo.setVisible(false);
        }

        if (checkBoxSi.isSelected() && checkBoxNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "¡Solo debe seleccionar si es llave primaria o no!", "Archivos", JOptionPane.ERROR_MESSAGE);
        } else if (TextFieldNombre.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "¡Nombre de Campo no puede ser vacío!", "Archivos", JOptionPane.ERROR_MESSAGE);
        } else if (size == 0) {
            JOptionPane.showMessageDialog(null, "¡Longitud no puede ser cero!", "Archivos", JOptionPane.ERROR_MESSAGE);
        } else if (checkBoxSi.isSelected() && !Main.key.equals("")) {
            JOptionPane.showMessageDialog(null, "¡Ya existe un campo clave!", "Archivos", JOptionPane.ERROR_MESSAGE);
        } else if (checkBoxSi.isSelected()) {
            Main.campos.add(new Campo(name, tipo, size, true));
            Main.key = name; //aqui ya guardo el nombre del campo que es llave primaria
            TextFieldNombre.setText("");
            jSpinner1.setValue(1);
            checkBoxSi.setSelected(false);
            checkBoxNo.setSelected(false);
            jLabel3.setVisible(true);
            checkBoxSi.setVisible(true);
            checkBoxNo.setVisible(true);
            JOptionPane.showMessageDialog(null, "¡Campo agregado exitosamente!", "Archivos", JOptionPane.INFORMATION_MESSAGE);
        } else if (checkBoxNo.isSelected()) {

            Main.campos.add(new Campo(name, tipo, size, false));
            TextFieldNombre.setText("");
            jSpinner1.setValue(1);
            checkBoxNo.setSelected(false);
            checkBoxSi.setSelected(false);
            JOptionPane.showMessageDialog(null, "¡Campo agregado exitosamente!", "Archivos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "¡Debe seleccionar si es llave primaria o no!", "Archivos", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_botonCrearMouseClicked

    private void borrarCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarCamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_borrarCamButtonActionPerformed

    private void regresarCamposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresarCamposMouseClicked

        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        jLabel6.setVisible(false);
        jLabel3.setVisible(false);
        botonCrear.setVisible(false);
        regresarCampos.setVisible(false);
        checkBoxSi.setVisible(false);
        checkBoxNo.setVisible(false);
        jSpinner1.setVisible(false);
        comboBoxTipo.setVisible(false);
        TextFieldNombre.setVisible(false);
        jLabel1.setVisible(true);
        crearCamposButton.setVisible(true);
        listarCamposButton.setVisible(true);
        modCamposButton.setVisible(true);
        borrarCamButton.setVisible(true);
        salirButton.setVisible(true);

    }//GEN-LAST:event_regresarCamposMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JButton borrarCamButton;
    private javax.swing.JButton botonCrear;
    private javax.swing.JCheckBox checkBoxNo;
    private javax.swing.JCheckBox checkBoxSi;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JButton crearCamposButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JDialog jListarCampos;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JButton listarCamposButton;
    private javax.swing.JButton modCamposButton;
    private javax.swing.JButton regresarCampos;
    private javax.swing.JButton salirButton;
    // End of variables declaration//GEN-END:variables
}
